-- Generated by Matugen. Do not edit the generated conf/colors.lua directly.
return {
    image = "{{image}}",
<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}
